### ISSUE TITLE
Error with dieresis in expected cfdi

### ISSUE THREAD

**Issue by andreagidaltig** [Vauxoo/pre-commit-vauxoo#130] opened 2023-11-29 22:05 UTC
I'm working in the module l10n_mx_edi_payslip in v17 and I got an error with dieresis in the expected_cfdi.xml file used in unit tests. It is expected that dieresis are used in this file because it's the structure requested for fiscal uses, so it can't be removed.

This is the error in pipelines:
https://git.vauxoo.com/vauxoo-dev/l10n-mx-payroll/-/jobs/1446371#L51

**Comment by andreagidaltig** [comment] 2023-11-29 22:09
Hi @antonag32 could you help me with this please?

**Comment by luisg123v** [comment] 2023-11-29 23:25
Hi @andreagidaltig,

Could you share the relevant part of the pipeline as code, please?

Take into account jobs could be erased at any time.

**Comment by luisg123v** [comment] 2023-11-29 23:45
AFAIK this is due to https://github.com/prettier/plugin-xml/issues/607, which in turn is caused by https://github.com/SAP/xml-tools/issues/407. If that's the case, there's not too much we could do our side.

I'd recommend implementing a solution similar to [this one](https://git.vauxoo.com/vauxoo/mexico/-/commit/c1cf897a371e14d4baea3cba83f8b516acf666c9), i.e. using a `.prettierignore` file.

Because of the above, I'm therefore closing this issue as unfixeable. However, feel free to comment if you think I'm mistaking on this.

Regards,

**Closed by luisg123v** 2023-11-29 23:45 UTC
